"""Generate Appendix A.1: the full per-feature audit table as a LaTeX longtable.

Reads ONLY outputs/analysis/fidelity_audit/f1_fidelity.json (byte-identical to the 08-13 archive).
Writes thesis_writeup/chapters/A1_audit_table.tex (included by A_appendix.tex).
Run from repo root: python thesis_writeup/figures/src/gen_audit_table.py
"""
import json, os, io

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
SRC = os.path.join(REPO, "outputs", "analysis", "fidelity_audit", "f1_fidelity.json")
OUT = os.path.join(REPO, "thesis_writeup", "chapters", "A1_audit_table.tex")

d = json.load(open(SRC))
blind = set(d["lists"]["blind_spots_4c"])
spur = set(d["lists"]["spurious_channels_4c"])
MNAR = {"QRS_duration_ms", "QT_interval_ms", "P_duration_ms"}

def verdict(name):
    v = []
    if name in blind: v.append("blind spot")
    if name in spur: v.append("spurious")
    if name in MNAR: v.append("MNAR$^{\\mathrm{m}}$")
    return ", ".join(v)

def esc(n):
    return n.replace("_", "\\_")

rows = []
for f in d["features"]:
    n = f["name"]
    note = " (= T\\_amp\\_II)" if n == "T_amplitude_mV" else ""
    rows.append((n, esc(n) + note,
                 f["eta2_4c_sim"], f["eta2_4c_sim_ci"], f["eta2_4c_real"], f["eta2_4c_real_ci"],
                 f["diff_4c_real_minus_sim"], f["diff_4c_ci"],
                 f["smd_real_minus_sim"], verdict(n)))
ax = d["axis"]
rows.append(("zz_axis", "frontal QRS axis (circular)",
             ax["eta2_4c_sim"], ax["eta2_4c_sim_ci"], ax["eta2_4c_real"], ax["eta2_4c_real_ci"],
             ax["diff_4c_real_minus_sim"], ax["diff_4c_ci"], None, "blind spot"))

L = []
L.append("% AUTO-GENERATED by thesis_writeup/figures/src/gen_audit_table.py from")
L.append("% outputs/analysis/fidelity_audit/f1_fidelity.json — do not edit by hand.")
L.append(r"\begin{small}")
L.append(r"\begin{longtable}{@{}l r r r r r@{}}")
L.append(r"\caption{The full informativeness-fidelity audit: four-class territory \etasq\ per feature in each domain (95\,\% block-bootstrap CIs), the sim--real difference, the standardised mean difference of the feature's marginal, and the confirmed verdict. Blind spot = real-informative, simulator-flat (difference CI $>0$); spurious = the reverse (CI $<0$); $^{\mathrm{m}}$ = simulated \etasq\ MNAR-confounded (territory-dependent missingness). \texttt{T\_amplitude\_mV} duplicates \texttt{T\_amp\_II}. Source: \texttt{f1\_fidelity.json}, seed 20260813, 500 draws.}\label{app:audit-table}\\" )
L.append(r"\toprule feature & \etasq\ sim & \etasq\ real & $\Delta$ (real$-$sim) & SMD & verdict \\ \midrule \endfirsthead")
L.append(r"\toprule feature & \etasq\ sim & \etasq\ real & $\Delta$ (real$-$sim) & SMD & verdict \\ \midrule \endhead")
L.append(r"\bottomrule \endfoot")
for key, name, es, esci, er, erci, df, dfci, smd, v in rows:
    smds = f"{smd:+.2f}" if smd is not None else "---"
    L.append(f"{name} & {es:.4f} & {er:.4f} & ${df:+.4f}$ {{\\scriptsize$[{dfci[0]:+.3f},{dfci[1]:+.3f}]$}} & {smds} & {v} \\\\")
L.append(r"\end{longtable}")
L.append(r"\end{small}")
io.open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote", OUT, "rows:", len(rows))
